"""add user foreign key

Revision ID: d7dbf20aa108
Revises: 3242981b80e9
Create Date: 2026-05-17 21:43:48.473120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7dbf20aa108'
down_revision: Union[str, Sequence[str], None] = '3242981b80e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_id_db', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'users', ['user_id_db'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'user_id_db')
    # ### end Alembic commands ###
