"""fix save_messages - user_id_db

Revision ID: fca3f107ecad
Revises: d7dbf20aa108
Create Date: 2026-05-17 22:33:53.515832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fca3f107ecad'
down_revision: Union[str, Sequence[str], None] = 'd7dbf20aa108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
